export enum MineralKeys {
  Calcium = "calcium",
  Iron = "iron",
  Magnesium = "magnesium",
  Phosphorus = "phosphorus",
  Potassium = "potassium",
  Sodium = "sodium",
  Zinc = "zinc",
  Copper = "copper",
  Manganese = "manganese",
  Selenium = "selenium",
  Fluoride = "fluoride",
  Iodine = "iodine",
  Chromium = "chromium",
  Molybdenum = "molybdenum",
}
