export enum VitaminKeys {
  VitaminA = "vitaminA",
  VitaminB1 = "vitaminB1",
  VitaminB2 = "vitaminB2",
  VitaminB3 = "vitaminB3",
  VitaminB5 = "vitaminB5",
  VitaminB6 = "vitaminB6",
  VitaminB7 = "vitaminB7",
  VitaminB9 = "vitaminB9",
  VitaminB12 = "vitaminB12",
  VitaminC = "vitaminC",
  VitaminD = "vitaminD",
  VitaminE = "vitaminE",
  VitaminK = "vitaminK",
}
